### ISSUE TITLE
What's the benefit of IRepository versus a more explicit IInventoryRepository?

### ISSUE THREAD

**Issue by jorbor** [nryckman/InventorySystem#3]
Also, why isn't IRepository used?

**Comment by nryckman** [comment]
My apologies. This was an unfinished piece in my code. 

In a realistic environment, I would have IInventoryRepository extend IRepository and InventoryRepository implement IInventoryRepository. Then through dependency injection, use the interface.

In theory, IRepository can abstract away SQL vs NoSQL logic (including tech and vendor specific differences).

While doing the project, the trade-off I was deciding on was speed and simplicity vs thoroughness of project. I wasn't exactly sure what the deadline and scope for this project was ( e.g. "In memory data structure is okay (no database code needed)" ), so I left the data layer less thoroughly implemented than the other layers of the stack.

A more realistic version of what I would do for a completely fresh, production ready project can be found at, https://github.com/nryckman/Heinz95729 . I really liked Andrew Wright's (Chief Software Architect of Acatar) implementation of SOLID principles in .NET.

Of course, the trade-off is more complexity ( couchbase set-up, elasticsearch set-up, seed data, lots of NuGet packages, and a couple Github repo libraries ).

I can send you instructions for installing the Heinz95729  repo if you would like to check it out. Alternatively, I could update this repo with some of the technologies I would use in a production environment if you would be interested.

**Comment by jorbor** [comment]
Thanks, that's good. I'll take a look at the other project. In-memory repo is perfect.
